version: "3"

services:
  catbus_directory:
    container_name: catbus_directory
    build:
      context: ../
      dockerfile: docker/directory/Dockerfile
    restart: always
    network_mode: host

  logserver:
    container_name: logserver
    build:
      context: ../
      dockerfile: docker/logserver/Dockerfile
    restart: always
    network_mode: host

  timezone:
    container_name: timezone
    build:
      context: ../
      dockerfile: docker/timezone_service/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
  weather:
    container_name: weather
    build:
      context: ../
      dockerfile: docker/weather/Dockerfile
    restart: always
    network_mode: host

  datalogger:
    container_name: datalogger
    build:
      context: ../
      dockerfile: docker/datalogger/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - /etc/chromatron/datalogger.cfg:/app/datalogger.cfg

  homeassistant_bridge:
    container_name: homeassistant_bridge
    build:
      context: ../
      dockerfile: docker/ha_bridge/Dockerfile
    restart: always
    network_mode: host